title: Ivan Sarno
description: PhD student at CEA Grenoble
baseurl: ""
url: https://ivansarno.github.io

theme: cvless

# site settings
taglong: PhD student at CEA Grenoble, working on Post-Quantum Cryptography for RISC-V
tagshort: PhD student at CEA Grenoble

# author settings
author:
  name: Ivan Sarno
  email: ivansarno@outlook.com
photo: assets/files/photo.jpg
# joblines:
#   - University of Jekyll
#   - Department of Themes
#   - 123 Main St, Anytown, USA
address: false #Foobar Hall 1.23
phone: false #+1 234 567 890

# profile links
profile:
  facebook: false #https://www.facebook.com/username
  x: false #https://x.com/username
  mastodon: false #https://mastodon.social/@username
  bluesky: false #https://bsky.app/profile/username.bsky.social
  instagram: false #https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/ivan-sarno/
  #scholar: https://scholar.google.com/citations?user=z7mfs78AAAAJ
  xing: false #https://www.xing.com/profile/username
  stackoverflow: false #https://stackoverflow.com/users/0000000/username
  medium: false #https://medium.com/@username
  github: https://github.com/ivansarno
  orcid: https://orcid.org/0009-0003-6447-3587
  cv: false

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never


